---
- name: This playbook istall apache2 on ubuntu server
  hosts: dbservers
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
  - name : start apache service
    service:
      name: apache2
      state: started
