---
- name: this playbook will install packages
  hosts: all
  become: true
    #gather_facts: no
  tasks:
  - name: install packages
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
      #tags: install_apache
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
      #tags: start_apache
    ignore_errors: yes
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
      #tags: install_apache
  - name : start apache service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
      #tags: start_apache
  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
