---
- name: this playbook will install packages
  hosts: all
  become: true
  vars:
    port: 8082
    #gather_facts: no
  tasks:
  - name: install packages httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
      #tags: install_apache
    notify: start httpd service
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
      #tags: install_apache
    notify: start apache service
  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
  - name: ensure that redhat apache listens on port {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: 'Listen {{ port }}'
    when: ansible_os_family == "RedHat"
    notify: restart apache
  - name: ensure apache2 listens at port {{ port }}
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '# /etc/apache2/sites-enabled/000-default.conf '
      line: 'Listen {{ port }}'
    when: ansible_os_family == "Debian"
    notify: restart apache2
  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
        #when: ansible_os_family == "RedHat"
      #tags: start_apache
      #ignore_errors: yes
  - name : start apache service
    service:
      name: apache2
      state: started
        #when: ansible_os_family == "Debian"
      #tags: start_apache
  - name: restart apache
    service:
      name: httpd
      state: restarted
    #when: ansible_os_family == "RedHat"
  - name: restart apache2
    service:
      name: apache2
      state: restarted
    #when: ansible_os_family == "Debian"
