---
# tasks file for setup_apache
- name: install package httpd
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
      #tags: install_apache
  notify: start httpd service
- name: install apache2
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
      #tags: install_apache
  notify: start apache service
- name: copy index.html
  copy:
    src: /opt/ansible/index.html
    dest: /var/www/html
    mode: 0666
- name: ensure redhat apache listens at port {{ port }}
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen {{ port }}'
  when: ansible_os_family == "RedHat"
  notify: restart apache
- name: ensure apache2 listens at port 8081
  lineinfile: 
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    insertafter: '# /etc/apache2/sites-enabled/000-default.conf '
    line: 'Listen {{ port }}'
  when: ansible_os_family == "Debian"
  notify: restart apache2
